// <auto-generated />
using CatchMeIfYouKnowAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatchMeIfYouKnowAPI.Data.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CatchMeIfYouKnowAPI.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Elbrus",
                            Content = "Najvisi vrh Evrope?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Mont Everest",
                            Content = "Najvisi vrh Azije?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Kilimandzaro",
                            Content = "Najvisi vrh Afrike?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
